#!/bin/bash


echo "enter a number 1"     #asking user to enter a number 1 

read num1            #declaring  variable num1 to store number1 enter by user

echo "enter a number 2"     #asking user to enter a number 2

read num2            #declaring variable num2 to store number2 enter by user


echo "select option  + - * / "   #asking user to  select option to perform a task

read selected_option  #declaring varibale selected_option to store option enter by user

if[$selected_option -eq +]:
then 
	num3 = num1 + num2 
	echo $num3
fi


#

